### PR TITLE
Fix slides

### PR DESCRIPTION
**Pull request by stevekinney**
The slides weren't be styled for some reason. So, I fixed it.

### CODE REVIEW

**Comment by erindepew** [comment]
@stevekinney @cfarm was this ever resolved? I'm also having trouble with the reveal submodule not being integrated properly.

**Comment by Roenok** [comment]
I merged this change in. In general, though, we are trying to move away from submodules because they complicate the repo and tend to spawn error messages.

**Comment by erindepew** [comment]
@Roenok completely agree, would we be able to use a non-custom version of reveal for this and just use NPM ?

**Comment by Roenok** [comment]
@erindepew We have a template repo with our custom version of reveal: https://github.com/girldevelopit/gdi-slides-template. We just have people include the reveal.js plugin directly in the repo, so there is no need to use an package manager: just download a zip and open the slides. Many of our students are beginners, so we want there to be as little friction as possible.

When these slides are ready to "graduate" to the main repo, I'll move the contents over the standard template.

**Comment by erindepew** [comment]
@Roenok 👌 thanks for clarifying!

**Pull request merged**
